# Generated by Django 3.0.8 on 2020-08-13 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20200730_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('valid_from', models.DateField()),
                ('valid_To', models.DateField()),
                ('discount', models.ImageField(default=0, upload_to='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
