# Generated by Django 3.0.8 on 2020-08-14 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0006_auto_20200813_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='discount_type',
            field=models.CharField(choices=[('R', 'Rupees'), ('P', 'Percent')], default='R', max_length=1),
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_place_order', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_code', to='shopping.CouponCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
