# Generated by Django 3.0.8 on 2020-08-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_couponcode_code_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
