# Generated by Django 3.0.8 on 2020-08-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_auto_20200819_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
