# Generated by Django 3.0.8 on 2020-09-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_address_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordered',
            old_name='date_time',
            new_name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='cart_item',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('cart_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shopping.CartItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='shopping.Ordered')),
            ],
        ),
    ]
