# Generated by Django 3.0.8 on 2020-09-02 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_auto_20200902_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='shopping.Address'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='shopping.Address'),
        ),
    ]
