# Generated by Django 3.0.8 on 2020-09-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0026_auto_20200907_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
