# Generated by Django 3.0.8 on 2020-09-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0027_cart_total_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
