# Generated by Django 3.0.8 on 2020-09-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0031_auto_20200917_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
