# Generated by Django 3.0.8 on 2020-09-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0034_auto_20200917_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
